-- Migration: Acreditacion SUA Colombia (Res 5095/2018) + JCI Standards
-- EstrateGIA v2.1 - Health Accreditation Module
-- Run: mysql -u emilio -ps1gma estrategia_v1 < database/migration_acreditacion_sua.sql

-- Fix missing column for file uploads
ALTER TABLE cal_evidencias_acreditacion ADD COLUMN IF NOT EXISTS evidencia_archivo_url VARCHAR(500) NULL;

-- Add scoring scale support
ALTER TABLE cal_estandares_acreditacion ADD COLUMN IF NOT EXISTS estandar_escala ENUM('0-100','0-10','1-5','cumple_parcial_no') DEFAULT '0-100';
ALTER TABLE cal_estandares_acreditacion ADD COLUMN IF NOT EXISTS estandar_servicio_id INT NULL;

-- Visits table
CREATE TABLE IF NOT EXISTS cal_acreditacion_visitas (
    visita_id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    ciclo_id INT NULL,
    visita_tipo ENUM('autoevaluacion','visita_evaluacion','seguimiento','reacreditacion') DEFAULT 'visita_evaluacion',
    visita_fecha_programada DATE,
    visita_fecha_real DATE,
    visita_evaluador_lider VARCHAR(200),
    visita_evaluadores TEXT COMMENT 'JSON array of evaluator names',
    visita_hallazgos INT DEFAULT 0,
    visita_no_conformidades INT DEFAULT 0,
    visita_observaciones INT DEFAULT 0,
    visita_informe_url VARCHAR(500),
    visita_estado ENUM('programada','en_curso','completada','cancelada') DEFAULT 'programada',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_empresa_ciclo (empresa_id, ciclo_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Structured improvement plans
CREATE TABLE IF NOT EXISTS cal_planes_mejora (
    plan_id INT AUTO_INCREMENT PRIMARY KEY,
    empresa_id INT NOT NULL,
    estandar_id INT,
    visita_id INT NULL,
    plan_accion TEXT NOT NULL,
    plan_responsable_id INT,
    plan_fecha_compromiso DATE,
    plan_fecha_cierre DATE,
    plan_evidencia_cierre TEXT,
    plan_estado ENUM('abierto','en_progreso','cerrado','vencido') DEFAULT 'abierto',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_empresa_estandar (empresa_id, estandar_id),
    CONSTRAINT fk_plan_estandar FOREIGN KEY (estandar_id) REFERENCES cal_estandares_acreditacion(estandar_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Follow-up tracking
CREATE TABLE IF NOT EXISTS cal_seguimiento (
    seguimiento_id INT AUTO_INCREMENT PRIMARY KEY,
    plan_id INT NOT NULL,
    seguimiento_fecha DATE NOT NULL,
    seguimiento_avance DECIMAL(5,1) DEFAULT 0,
    seguimiento_observaciones TEXT,
    seguimiento_evidencia_url VARCHAR(500),
    seguimiento_usuario_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_plan (plan_id),
    CONSTRAINT fk_seguimiento_plan FOREIGN KEY (plan_id) REFERENCES cal_planes_mejora(plan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- SUA official standards (Res 5095/2018) - seed 160+ standards
CREATE TABLE IF NOT EXISTS cal_estandares_sua (
    sua_id INT AUTO_INCREMENT PRIMARY KEY,
    sua_grupo VARCHAR(100) NOT NULL COMMENT 'Official SUA group',
    sua_subgrupo VARCHAR(100),
    sua_codigo VARCHAR(20) NOT NULL,
    sua_numero INT NOT NULL,
    sua_descripcion TEXT NOT NULL,
    sua_tipo ENUM('indispensable','complementario','informacion') DEFAULT 'indispensable',
    sua_eje ENUM('seguridad_paciente','humanizacion','gestion_tecnologia','enfoque_riesgo') DEFAULT 'seguridad_paciente',
    UNIQUE KEY uk_codigo (sua_codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO cal_estandares_sua (sua_grupo, sua_subgrupo, sua_codigo, sua_numero, sua_descripcion, sua_tipo, sua_eje) VALUES
-- EJE: SEGURIDAD DEL PACIENTE
('Derechos de los pacientes','Carta de derechos','SUA-DP-001',1,'La organizacion tiene definida y divulgada la carta de derechos y deberes de los pacientes','indispensable','seguridad_paciente'),
('Derechos de los pacientes','Informacion al paciente','SUA-DP-002',2,'El paciente y su familia reciben informacion completa sobre diagnostico, tratamiento y pronostico','indispensable','seguridad_paciente'),
('Derechos de los pacientes','Consentimiento informado','SUA-DP-003',3,'Se obtiene consentimiento informado para procedimientos quirurgicos y de alto riesgo','indispensable','seguridad_paciente'),
('Seguridad del paciente','Identificacion correcta','SUA-SP-001',4,'Se implementa protocolo de identificacion correcta de pacientes en todos los servicios','indispensable','seguridad_paciente'),
('Seguridad del paciente','Comunicacion efectiva','SUA-SP-002',5,'Se implementan barreras de seguridad para comunicacion efectiva entre el equipo de salud','indispensable','seguridad_paciente'),
('Seguridad del paciente','Medicamentos alto riesgo','SUA-SP-003',6,'Se implementan protocolos para manejo seguro de medicamentos de alto riesgo','indispensable','seguridad_paciente'),
('Seguridad del paciente','Cirugia segura','SUA-SP-004',7,'Se aplica lista de verificacion de cirugia segura en todos los procedimientos quirurgicos','indispensable','seguridad_paciente'),
('Seguridad del paciente','Prevencion infecciones','SUA-SP-005',8,'Se implementa programa de prevencion y control de infecciones asociadas a la atencion en salud','indispensable','seguridad_paciente'),
('Seguridad del paciente','Prevencion caidas','SUA-SP-006',9,'Se implementa programa de prevencion de caidas en pacientes hospitalizados','complementario','seguridad_paciente'),
('Seguridad del paciente','Prevencion ulceras','SUA-SP-007',10,'Se implementa protocolo de prevencion de ulceras por presion','complementario','seguridad_paciente'),
('Seguridad del paciente','Eventos adversos','SUA-SP-008',11,'Se cuenta con sistema de reporte, analisis y gestion de eventos adversos','indispensable','seguridad_paciente'),
('Seguridad del paciente','Barreras de seguridad','SUA-SP-009',12,'Se implementan barreras de seguridad en todos los procesos asistenciales criticos','indispensable','seguridad_paciente'),
('Acceso','Oportunidad consulta','SUA-AC-001',13,'La organizacion garantiza tiempos de espera definidos para consulta externa','indispensable','seguridad_paciente'),
('Acceso','Oportunidad urgencias','SUA-AC-002',14,'Se implementa sistema de triage estructurado en el servicio de urgencias','indispensable','seguridad_paciente'),
('Acceso','Oportunidad cirugia','SUA-AC-003',15,'Se garantizan tiempos de espera definidos para procedimientos quirurgicos programados','indispensable','seguridad_paciente'),
('Acceso','Referencia contrarreferencia','SUA-AC-004',16,'Se implementa sistema de referencia y contrarreferencia de pacientes','indispensable','seguridad_paciente'),
('Registro e ingreso','Admisiones','SUA-RI-001',17,'El proceso de admision garantiza registro completo y veraz de datos del paciente','indispensable','seguridad_paciente'),
('Evaluacion de necesidades','Valoracion inicial','SUA-EN-001',18,'Todo paciente recibe valoracion inicial completa por profesional competente al ingreso','indispensable','seguridad_paciente'),
('Evaluacion de necesidades','Valoracion riesgo','SUA-EN-002',19,'Se realiza valoracion de riesgo (caidas, ulceras, nutricional, funcional) al ingreso','complementario','seguridad_paciente'),
('Planeacion atencion','Plan de cuidado','SUA-PA-001',20,'Se elabora plan de cuidado individualizado para cada paciente hospitalizado','indispensable','seguridad_paciente'),
('Ejecucion tratamiento','Administracion medicamentos','SUA-ET-001',21,'Se aplican los 10 correctos en la administracion de medicamentos','indispensable','seguridad_paciente'),
('Ejecucion tratamiento','Procedimientos','SUA-ET-002',22,'Los procedimientos diagnosticos y terapeuticos se realizan segun protocolos establecidos','indispensable','seguridad_paciente'),
('Evaluacion atencion','Revaloracion','SUA-EA-001',23,'Se realiza revaloracion periodica del paciente durante su estancia hospitalaria','indispensable','seguridad_paciente'),
('Continuidad atencion','Plan de egreso','SUA-CA-001',24,'Se elabora plan de egreso con recomendaciones, medicamentos y seguimiento','indispensable','seguridad_paciente'),
('Continuidad atencion','Seguimiento post-egreso','SUA-CA-002',25,'Se realiza seguimiento post-egreso a pacientes de alto riesgo','complementario','seguridad_paciente'),
-- EJE: HUMANIZACION
('Humanizacion','Trato digno','SUA-HU-001',26,'La organizacion garantiza trato digno y respetuoso a pacientes y familias','indispensable','humanizacion'),
('Humanizacion','Acompanamiento','SUA-HU-002',27,'Se facilita el acompanamiento del paciente por familiar o cuidador durante la atencion','indispensable','humanizacion'),
('Humanizacion','Informacion comprensible','SUA-HU-003',28,'La informacion al paciente se proporciona en lenguaje claro y comprensible','indispensable','humanizacion'),
('Humanizacion','Privacidad','SUA-HU-004',29,'Se garantiza la privacidad y confidencialidad del paciente en todos los espacios de atencion','indispensable','humanizacion'),
('Humanizacion','Entorno fisico','SUA-HU-005',30,'El entorno fisico promueve el bienestar del paciente (iluminacion, ruido, senalizacion)','complementario','humanizacion'),
-- EJE: GESTION DE LA TECNOLOGIA
('Gestion de tecnologia','Mantenimiento equipos','SUA-GT-001',31,'Se implementa programa de mantenimiento preventivo y correctivo de equipos biomedicos','indispensable','gestion_tecnologia'),
('Gestion de tecnologia','Tecnovigilancia','SUA-GT-002',32,'Se implementa programa de tecnovigilancia para reporte de eventos adversos con dispositivos medicos','indispensable','gestion_tecnologia'),
('Gestion de tecnologia','Capacitacion','SUA-GT-003',33,'El personal recibe capacitacion periodica en el uso seguro de tecnologia biomedica','indispensable','gestion_tecnologia'),
('Gestion de tecnologia','Evaluacion tecnologia','SUA-GT-004',34,'Se realiza evaluacion de tecnologia antes de la adquisicion de nuevos equipos','complementario','gestion_tecnologia'),
-- EJE: ENFOQUE DE RIESGO
('Enfoque de riesgo','Gestion del riesgo','SUA-ER-001',35,'La organizacion cuenta con politica y programa de gestion integral del riesgo','indispensable','enfoque_riesgo'),
('Enfoque de riesgo','Mapa de riesgos','SUA-ER-002',36,'Se cuenta con mapa de riesgos actualizado por proceso asistencial y administrativo','indispensable','enfoque_riesgo'),
('Enfoque de riesgo','Planes de contingencia','SUA-ER-003',37,'Se implementan planes de contingencia para los principales riesgos identificados','indispensable','enfoque_riesgo'),
('Enfoque de riesgo','Analisis de modo de fallo','SUA-ER-004',38,'Se aplica metodologia AMFE (Analisis de Modo de Fallo y Efecto) en procesos criticos','complementario','enfoque_riesgo'),
-- GESTION ORGANIZACIONAL
('Direccionamiento estrategico','Planeacion','SUA-DE-001',39,'La organizacion cuenta con plataforma estrategica documentada y desplegada','indispensable','seguridad_paciente'),
('Direccionamiento estrategico','Indicadores','SUA-DE-002',40,'Se cuenta con sistema de indicadores de gestion alineados con la estrategia','indispensable','seguridad_paciente'),
('Gerencia del talento humano','Seleccion','SUA-GH-001',41,'El proceso de seleccion garantiza la idoneidad del personal asistencial','indispensable','seguridad_paciente'),
('Gerencia del talento humano','Capacitacion continua','SUA-GH-002',42,'Se implementa programa de educacion continuada para todo el personal','indispensable','seguridad_paciente'),
('Gerencia del talento humano','Evaluacion desempeno','SUA-GH-003',43,'Se realiza evaluacion periodica del desempeno del personal asistencial','complementario','seguridad_paciente'),
('Gerencia de la informacion','Historia clinica','SUA-GI-001',44,'Se garantiza la integridad, seguridad y disponibilidad de la historia clinica','indispensable','seguridad_paciente'),
('Gerencia de la informacion','Analisis de datos','SUA-GI-002',45,'Se utilizan los datos clinicos para la toma de decisiones y mejora continua','indispensable','seguridad_paciente'),
('Gestion de la calidad','Sistema de calidad','SUA-GC-001',46,'Se implementa un sistema de gestion de la calidad documentado y evaluado periodicamente','indispensable','seguridad_paciente'),
('Gestion de la calidad','Auditoria interna','SUA-GC-002',47,'Se realiza auditoria interna de calidad con periodicidad minima anual','indispensable','seguridad_paciente'),
('Gestion de la calidad','Mejora continua','SUA-GC-003',48,'Se implementan ciclos de mejora continua (PHVA) en todos los procesos','indispensable','seguridad_paciente'),
('Gestion de la calidad','PAMEC','SUA-GC-004',49,'Se implementa el Programa de Auditoria para el Mejoramiento de la Calidad (PAMEC)','indispensable','seguridad_paciente'),
('Gestion del ambiente fisico','Infraestructura','SUA-AF-001',50,'La infraestructura fisica cumple con los requisitos de habilitacion y seguridad','indispensable','seguridad_paciente'),
('Gestion del ambiente fisico','Emergencias','SUA-AF-002',51,'Se implementa plan hospitalario de emergencias con simulacros periodicos','complementario','seguridad_paciente'),
-- JCI STANDARDS (Joint Commission International)
('JCI - Metas internacionales','IPSG.1','JCI-IPSG-001',52,'Identificar correctamente a los pacientes','indispensable','seguridad_paciente'),
('JCI - Metas internacionales','IPSG.2','JCI-IPSG-002',53,'Mejorar la comunicacion efectiva','indispensable','seguridad_paciente'),
('JCI - Metas internacionales','IPSG.3','JCI-IPSG-003',54,'Mejorar la seguridad de los medicamentos de alto riesgo','indispensable','seguridad_paciente'),
('JCI - Metas internacionales','IPSG.4','JCI-IPSG-004',55,'Garantizar cirugias en el lugar correcto, con el procedimiento correcto y al paciente correcto','indispensable','seguridad_paciente'),
('JCI - Metas internacionales','IPSG.5','JCI-IPSG-005',56,'Reducir el riesgo de infecciones asociadas con la atencion en salud','indispensable','seguridad_paciente'),
('JCI - Metas internacionales','IPSG.6','JCI-IPSG-006',57,'Reducir el riesgo de dano al paciente por causa de caidas','indispensable','seguridad_paciente'),
('JCI - ACC','ACC.1','JCI-ACC-001',58,'Se tamiza y evaluan las necesidades de los pacientes','indispensable','seguridad_paciente'),
('JCI - ACC','ACC.2','JCI-ACC-002',59,'La atencion se planifica para satisfacer las necesidades del paciente','indispensable','seguridad_paciente'),
('JCI - ACC','ACC.3','JCI-ACC-003',60,'Se implementan procesos para el acceso a la atencion y continuidad','indispensable','seguridad_paciente'),
('JCI - ACC','ACC.4','JCI-ACC-004',61,'El alta, la transferencia y la derivacion se planifican y coordinan','indispensable','seguridad_paciente'),
('JCI - ACC','ACC.5','JCI-ACC-005',62,'El transporte de pacientes se realiza de forma segura','indispensable','seguridad_paciente'),
('JCI - Derechos del paciente','PFR.1','JCI-PFR-001',63,'La organizacion protege los derechos del paciente y su familia','indispensable','humanizacion'),
('JCI - Derechos del paciente','PFR.2','JCI-PFR-002',64,'Se informa a los pacientes y sus familias sobre sus derechos y responsabilidades','indispensable','humanizacion'),
('JCI - Derechos del paciente','PFR.3','JCI-PFR-003',65,'Se obtiene consentimiento informado','indispensable','humanizacion'),
('JCI - Derechos del paciente','PFR.4','JCI-PFR-004',66,'Se informa a los pacientes sobre sus derechos a participar en investigaciones','complementario','humanizacion'),
('JCI - Evaluacion del paciente','AOP.1','JCI-AOP-001',67,'La evaluacion del paciente es integral y multidisciplinaria','indispensable','seguridad_paciente'),
('JCI - Evaluacion del paciente','AOP.2','JCI-AOP-002',68,'Se realizan evaluaciones de laboratorio, imagenologia y diagnostico segun necesidades','indispensable','seguridad_paciente'),
('JCI - Atencion del paciente','COP.1','JCI-COP-001',69,'La atencion se proporciona segun el plan de cuidado individualizado','indispensable','seguridad_paciente'),
('JCI - Atencion del paciente','COP.2','JCI-COP-002',70,'Los procedimientos de alto riesgo se rigen por politicas y procedimientos','indispensable','seguridad_paciente'),
('JCI - Atencion del paciente','COP.3','JCI-COP-003',71,'Los alimentos y la terapia nutricional satisfacen las necesidades del paciente','complementario','seguridad_paciente'),
('JCI - Atencion del paciente','COP.4','JCI-COP-004',72,'El manejo del dolor se realiza segun guias clinicas','complementario','seguridad_paciente'),
('JCI - Atencion del paciente','COP.5','JCI-COP-005',73,'La atencion al final de la vida respeta las necesidades y preferencias del paciente','complementario','humanizacion'),
('JCI - Educacion del paciente','PFE.1','JCI-PFE-001',74,'La educacion del paciente y su familia apoya la participacion en las decisiones','indispensable','humanizacion'),
('JCI - Educacion del paciente','PFE.2','JCI-PFE-002',75,'Se evalua la comprension de la educacion proporcionada','indispensable','humanizacion'),
('JCI - Manejo medicamentos','MMU.1','JCI-MMU-001',76,'La organizacion cuenta con un sistema de gestion de medicamentos','indispensable','seguridad_paciente'),
('JCI - Manejo medicamentos','MMU.2','JCI-MMU-002',77,'La seleccion y adquisicion de medicamentos se realiza segun lista institucional','indispensable','seguridad_paciente'),
('JCI - Manejo medicamentos','MMU.3','JCI-MMU-003',78,'El almacenamiento de medicamentos cumple con condiciones de seguridad','indispensable','seguridad_paciente'),
('JCI - Manejo medicamentos','MMU.4','JCI-MMU-004',79,'La prescripcion, transcripcion y administracion son seguras','indispensable','seguridad_paciente'),
('JCI - Manejo medicamentos','MMU.5','JCI-MMU-005',80,'Se realiza monitoreo de los efectos de los medicamentos','indispensable','seguridad_paciente'),
('JCI - Gestion calidad','QPS.1','JCI-QPS-001',81,'La organizacion cuenta con un enfoque integral de gestion de calidad y seguridad','indispensable','seguridad_paciente'),
('JCI - Gestion calidad','QPS.2','JCI-QPS-002',82,'Se disenan procesos clinicos y gerenciales nuevos o modificados','indispensable','seguridad_paciente'),
('JCI - Gestion calidad','QPS.3','JCI-QPS-003',83,'Se realiza monitoreo de la calidad mediante indicadores','indispensable','seguridad_paciente'),
('JCI - Gestion calidad','QPS.4','JCI-QPS-004',84,'Se implementan actividades de mejora continua de la calidad','indispensable','seguridad_paciente'),
('JCI - Gestion calidad','QPS.5','JCI-QPS-005',85,'Se utiliza la gestion de riesgos para mejorar la seguridad','indispensable','seguridad_paciente'),
('JCI - Prevencion infecciones','PCI.1','JCI-PCI-001',86,'La organizacion tiene un programa integral de control de infecciones','indispensable','seguridad_paciente'),
('JCI - Prevencion infecciones','PCI.2','JCI-PCI-002',87,'Se implementan barreras de proteccion y aislamiento segun normas','indispensable','seguridad_paciente'),
('JCI - Prevencion infecciones','PCI.3','JCI-PCI-003',88,'El programa de control de infecciones se integra con la gestion de calidad','indispensable','seguridad_paciente'),
('JCI - Gobierno clinico','GLD.1','JCI-GLD-001',89,'La direccion es responsable del cumplimiento de la mision y calidad','indispensable','seguridad_paciente'),
('JCI - Gobierno clinico','GLD.2','JCI-GLD-002',90,'Se cuenta con un organigrama y estructura de gobierno clinico definida','indispensable','seguridad_paciente'),
('JCI - Gobierno clinico','GLD.3','JCI-GLD-003',91,'Las politicas y procedimientos guian la gestion de la organizacion','indispensable','seguridad_paciente'),
('JCI - Gestion instalaciones','FMS.1','JCI-FMS-001',92,'Las instalaciones cumplen con normas de seguridad y accesibilidad','indispensable','seguridad_paciente'),
('JCI - Gestion instalaciones','FMS.2','JCI-FMS-002',93,'Se implementa programa de mantenimiento de infraestructura','indispensable','seguridad_paciente'),
('JCI - Gestion instalaciones','FMS.3','JCI-FMS-003',94,'Se gestionan los residuos peligrosos y la bioseguridad','indispensable','seguridad_paciente'),
('JCI - Gestion instalaciones','FMS.4','JCI-FMS-004',95,'Se implementan planes de emergencias y desastres','indispensable','seguridad_paciente'),
('JCI - Gestion instalaciones','FMS.5','JCI-FMS-005',96,'La seguridad contra incendios esta garantizada','indispensable','seguridad_paciente'),
('JCI - Talento humano','SQE.1','JCI-SQE-001',97,'El personal cuenta con las competencias necesarias para sus funciones','indispensable','seguridad_paciente'),
('JCI - Talento humano','SQE.2','JCI-SQE-002',98,'Se verifica la formacion, experiencia y licencias del personal','indispensable','seguridad_paciente'),
('JCI - Talento humano','SQE.3','JCI-SQE-003',99,'Se realiza orientacion y capacitacion inicial al personal nuevo','indispensable','seguridad_paciente'),
('JCI - Talento humano','SQE.4','JCI-SQE-004',100,'Se realiza evaluacion del desempeno del personal','complementario','seguridad_paciente'),
('JCI - Informacion','MOI.1','JCI-MOI-001',101,'La historia clinica es unica, estandarizada y accesible','indispensable','seguridad_paciente'),
('JCI - Informacion','MOI.2','JCI-MOI-002',102,'Se protege la confidencialidad y seguridad de la informacion','indispensable','seguridad_paciente'),
('JCI - Informacion','MOI.3','JCI-MOI-003',103,'Se utilizan datos e informacion para la toma de decisiones','indispensable','seguridad_paciente'),
-- ISO 7101:2023 Health Quality Management
('ISO 7101 - Contexto','4.1','ISO71-001',104,'Se comprende la organizacion y su contexto en salud','indispensable','seguridad_paciente'),
('ISO 7101 - Contexto','4.2','ISO71-002',105,'Se comprenden las necesidades y expectativas de las partes interesadas','indispensable','seguridad_paciente'),
('ISO 7101 - Alcance','4.3','ISO71-003',106,'Se determina el alcance del sistema de gestion de calidad en salud','indispensable','seguridad_paciente'),
('ISO 7101 - Liderazgo','5.1','ISO71-004',107,'El liderazgo y compromiso de la alta direccion es demostrado','indispensable','seguridad_paciente'),
('ISO 7101 - Politica','5.2','ISO71-005',108,'La politica de calidad en salud es comunicada y entendida','indispensable','seguridad_paciente'),
('ISO 7101 - Roles','5.3','ISO71-006',109,'Los roles, responsabilidades y autoridades en la organizacion estan asignados','indispensable','seguridad_paciente'),
('ISO 7101 - Riesgos','6.1','ISO71-007',110,'Se determinan los riesgos y oportunidades del sistema de gestion','indispensable','seguridad_paciente'),
('ISO 7101 - Objetivos','6.2','ISO71-008',111,'Los objetivos de calidad en salud son coherentes con la politica','indispensable','seguridad_paciente'),
('ISO 7101 - Cambios','6.3','ISO71-009',112,'La planificacion de cambios se realiza de forma sistematica','complementario','seguridad_paciente'),
('ISO 7101 - Recursos','7.1','ISO71-010',113,'Se determinan y proporcionan los recursos necesarios','indispensable','seguridad_paciente'),
('ISO 7101 - Competencia','7.2','ISO71-011',114,'Se garantiza la competencia del personal que afecta la calidad','indispensable','seguridad_paciente'),
('ISO 7101 - Conciencia','7.3','ISO71-012',115,'El personal es consciente de la politica y objetivos de calidad','indispensable','seguridad_paciente'),
('ISO 7101 - Comunicacion','7.4','ISO71-013',116,'La comunicacion interna y externa es eficaz','indispensable','humanizacion'),
('ISO 7101 - Informacion documentada','7.5','ISO71-014',117,'La informacion documentada es controlada y mantenida','indispensable','seguridad_paciente'),
('ISO 7101 - Planificacion operativa','8.1','ISO71-015',118,'Se planifica, implementa y controla los procesos necesarios','indispensable','seguridad_paciente'),
('ISO 7101 - Requisitos','8.2','ISO71-016',119,'Se determinan los requisitos para los productos y servicios de salud','indispensable','seguridad_paciente'),
('ISO 7101 - Diseno','8.3','ISO71-017',120,'Se controla el diseno y desarrollo de productos y servicios','complementario','seguridad_paciente'),
('ISO 7101 - Control externo','8.4','ISO71-018',121,'Se controlan los procesos, productos y servicios externos','indispensable','seguridad_paciente'),
('ISO 7101 - Produccion','8.5','ISO71-019',122,'La produccion y provision del servicio se realiza bajo condiciones controladas','indispensable','seguridad_paciente'),
('ISO 7101 - Liberacion','8.6','ISO71-020',123,'La liberacion de productos y servicios cumple con los requisitos','indispensable','seguridad_paciente'),
('ISO 7101 - No conformidades','8.7','ISO71-021',124,'Las salidas no conformes se identifican y controlan','indispensable','seguridad_paciente'),
('ISO 7101 - Seguimiento','9.1','ISO71-022',125,'Se realiza seguimiento, medicion, analisis y evaluacion','indispensable','seguridad_paciente'),
('ISO 7101 - Auditoria','9.2','ISO71-023',126,'Las auditorias internas se realizan a intervalos planificados','indispensable','seguridad_paciente'),
('ISO 7101 - Revision direccion','9.3','ISO71-024',127,'La alta direccion revisa el sistema de gestion de calidad','indispensable','seguridad_paciente'),
('ISO 7101 - Mejora','10.1','ISO71-025',128,'Se determinan y seleccionan oportunidades de mejora','indispensable','seguridad_paciente'),
('ISO 7101 - NC y AC','10.2','ISO71-026',129,'Ante una no conformidad se toman acciones correctivas','indispensable','seguridad_paciente'),
('ISO 7101 - Mejora continua','10.3','ISO71-027',130,'Se mejora continuamente la conveniencia, adecuacion y eficacia del sistema','indispensable','seguridad_paciente'),
-- HABILITACION Resolucion 3100 (Standards for enabling health services)
('Habilitacion Res.3100','Talento humano','RES3100-001',131,'El personal asistencial cuenta con la formacion y certificacion requerida','indispensable','seguridad_paciente'),
('Habilitacion Res.3100','Infraestructura','RES3100-002',132,'La infraestructura cumple con las condiciones de accesibilidad y seguridad','indispensable','seguridad_paciente'),
('Habilitacion Res.3100','Dotacion','RES3100-003',133,'Los equipos biomedicos cuentan con mantenimiento y calibracion vigente','indispensable','gestion_tecnologia'),
('Habilitacion Res.3100','Medicamentos','RES3100-004',134,'Los medicamentos y dispositivos medicos se gestionan segun normativa','indispensable','seguridad_paciente'),
('Habilitacion Res.3100','Procesos prioritarios','RES3100-005',135,'Los procesos asistenciales prioritarios cuentan con guias y protocolos','indispensable','seguridad_paciente'),
('Habilitacion Res.3100','Historia clinica','RES3100-006',136,'Las historias clinicas cumplen con los requisitos de registro y conservacion','indispensable','seguridad_paciente'),
('Habilitacion Res.3100','Interdependencia','RES3100-007',137,'Se garantiza la disponibilidad de servicios de apoyo diagnostico y terapeutico','indispensable','seguridad_paciente'),
('Habilitacion Res.3100','Referencia','RES3100-008',138,'Se cuenta con red de prestadores para referencia y contrarreferencia','indispensable','seguridad_paciente'),
('Habilitacion Res.3100','Seguimiento riesgos','RES3100-009',139,'Se realiza seguimiento a riesgos en la atencion en salud','indispensable','enfoque_riesgo'),
('Habilitacion Res.3100','Eventos adversos','RES3100-010',140,'Se implementa programa de seguridad del paciente','indispensable','seguridad_paciente'),
-- ADDITIONAL SUA STANDARDS (Gestion organizacional extended)
('Gestion de calidad','PAMEC avanzado','SUA-GC-005',141,'El PAMEC incluye autoevaluacion, auditoria interna y externa con resultados documentados','indispensable','seguridad_paciente'),
('Gestion de calidad','Ciclo PHVA','SUA-GC-006',142,'Los ciclos PHVA se documentan con indicadores de resultado, proceso y estructura','indispensable','seguridad_paciente'),
('Gestion de calidad','Benchmarking','SUA-GC-007',143,'Se realizan comparaciones con instituciones de referencia (benchmarking) para mejora','complementario','seguridad_paciente'),
('Gestion del talento humano','Bienestar laboral','SUA-GH-004',144,'Se implementa programa de bienestar laboral y prevencion del burnout','complementario','humanizacion'),
('Gestion del talento humano','Clima organizacional','SUA-GH-005',145,'Se mide el clima organizacional con periodicidad minima anual','complementario','humanizacion'),
('Gestion del talento humano','Incentivos','SUA-GH-006',146,'Se cuenta con programa de incentivos por desempeno y calidad','complementario','humanizacion'),
('Gestion de la informacion','Interoperabilidad','SUA-GI-003',147,'Los sistemas de informacion permiten interoperabilidad entre servicios','complementario','gestion_tecnologia'),
('Gestion de la informacion','Trazabilidad','SUA-GI-004',148,'Se garantiza trazabilidad completa de la atencion del paciente en todos los servicios','indispensable','seguridad_paciente'),
('Gestion de la tecnologia','Seguridad digital','SUA-GT-005',149,'Se implementan politicas de seguridad digital y proteccion de datos clinicos','indispensable','gestion_tecnologia'),
('Gestion de la tecnologia','Innovacion','SUA-GT-006',150,'Se promueve la innovacion tecnologica para la mejora de la atencion','complementario','gestion_tecnologia'),
('Gestion del ambiente fisico','Sostenibilidad','SUA-AF-003',151,'La organizacion implementa practicas de sostenibilidad ambiental','complementario','enfoque_riesgo'),
('Gestion del ambiente fisico','Entornos seguros','SUA-AF-004',152,'Los entornos asistenciales son seguros para pacientes, familias y personal','indispensable','seguridad_paciente'),
('Enfoque de riesgo','Rondas de seguridad','SUA-ER-005',153,'Se realizan rondas de seguridad periodicas con participacion directiva','indispensable','enfoque_riesgo'),
('Enfoque de riesgo','Cultura de seguridad','SUA-ER-006',154,'Se mide y fomenta la cultura de seguridad del paciente en toda la organizacion','indispensable','enfoque_riesgo'),
('Enfoque de riesgo','Segundas victimas','SUA-ER-007',155,'Se implementa programa de apoyo a segundas victimas de eventos adversos','complementario','humanizacion'),
('Humanizacion','Atencion centrada','SUA-HU-006',156,'La atencion esta centrada en el paciente y su familia como eje del proceso','indispensable','humanizacion'),
('Humanizacion','Competencia cultural','SUA-HU-007',157,'La atencion respeta la diversidad cultural, etnica y de genero','complementario','humanizacion'),
('Humanizacion','Comunicacion asertiva','SUA-HU-008',158,'Se capacita al personal en comunicacion asertiva y habilidades interpersonales','complementario','humanizacion'),
('Humanizacion','Voluntariado','SUA-HU-009',159,'Se promueve el voluntariado como apoyo a la experiencia del paciente','complementario','humanizacion'),
('Direccionamiento estrategico','Responsabilidad social','SUA-DE-003',160,'La organizacion tiene definida y despliega su politica de responsabilidad social','complementario','humanizacion'),
('Direccionamiento estrategico','Transparencia','SUA-DE-004',161,'La organizacion publica resultados de calidad y seguridad para rendicion de cuentas','indispensable','seguridad_paciente'),
('Direccionamiento estrategico','Alianzas','SUA-DE-005',162,'Se establecen alianzas estrategicas con otros actores del sistema de salud','complementario','seguridad_paciente'),
('Seguridad del paciente','Rondas directivas','SUA-SP-010',163,'Las directivas realizan rondas periodicas de seguridad en los servicios','indispensable','seguridad_paciente'),
('Seguridad del paciente','Conciliacion medicamentosa','SUA-SP-011',164,'Se implementa conciliacion medicamentosa en todas las transiciones asistenciales','indispensable','seguridad_paciente'),
('Seguridad del paciente','Alarmas clinicas','SUA-SP-012',165,'Se gestionan adecuadamente las alarmas clinicas para prevenir fatiga de alarmas','complementario','seguridad_paciente');
